# Blog settings
permalink: /blog/:categories/:title

# My variables
name: \#root@bynx
description: bynx's personal blog - security research, CTFs, and tools
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "package.json", "package-lock.json", "Gemfile", "Gemfile.lock"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins
plugins:
  - jemoji

colors:
  black:     '#111111'
  white:     '#000000'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
